		<div class="main">
			<article class="paper" >
				<header class="form-header clearfix">
					<button onclick="return false;" class="print" title="Print this Form"> </button>
					<span class="form-language-selector"><span>Choose Language</span></span>
					<div class="form-progress" ></div>
					<a href="http://www.smap.com.au/" title="Smap">
						<div class="logo-wrapper">
							<img src="images/smap_logo.png" alt="logo">
						</div>
					</a>
				</header>