<aside class="side-slider">
	<button type="button" class="close" data-dismiss="side-slider" aria-hidden="true">×</button>
	<nav>
	</nav>
	<div class="content">
	</div>
</aside>

<button class="handle side-slider-toggle open"></button>
<button class="handle side-slider-toggle close"></button>
<div class="side-slider-toggle slider-overlay"></div>

<div class="main">
	<article class="paper" >
		<header class="form-header clearfix">
			<div class="offline-enabled">
			<div title="Records Queued" class="queue-length side-slider-toggle">0</div>	</div>
			<button onclick="return false;" class="print" title="Print this Form"> </button>
			<span class="form-language-selector"><span>Choose Language</span></span>
			<div class="form-progress" ></div>
			<a href="http://www.smap.com.au/" title="Smap">
				<div class="logo-wrapper">
					<img src="images/smap_logo.png" alt="logo">
				</div>
			</a>
		</header>