
	<head>
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600&subset=latin,cyrillic-ext,cyrillic,greek-ext,greek,vietnamese,latin-ext' rel='stylesheet' type='text/css'>
		<link type="text/css" href="css/libs/webform_formhub.css" media="all" rel="stylesheet" />
		<link type="text/css" href="css/libs/webform_print_formhub.css" media="print" rel="stylesheet" />

		<link rel="shortcut icon" href="images/favicon.ico">
		<!-- For third-generation iPad with high-resolution Retina display: -->
		<link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/fieldTask_144_144_min.png">
		<!-- For iPhone with high-resolution Retina display: -->
		<link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/fieldTask_114_114_min.png">
		<!-- For first- and second-generation iPad: -->
		<link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/fieldTask_72_72_min.png">
		<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
		<link rel="apple-touch-icon-precomposed" href="images/fieldTask_57_57_min.png">
		
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<!--[if lt IE 10]>
        	<script type="text/javascript">window.location = 'modern_browsers';</script>
		<![endif]-->
		
